// GENERATED — DO NOT EDIT.
// Tork PII country registry, bundle version 1.2.0 (content cfd4f61ebaf4).
// Source: landing/lib/pii/registry/ via scripts/pii/generate-sdk-registry.ts.
// Regenerate:  npx tsx scripts/pii/generate-sdk-registry.ts
// See generated/sdk-registry/README.md for the rules this data is fed to.

export interface TorkPiiPattern {
  name: string;
  country: string;
  kind: string;
  regex: RegExp;
  redaction: string;
  type: string;
  label: string;
  requiresKeyword: boolean;
  alwaysOn: boolean;
  keywords: string[];
  wholeWordKeywords: string[];
  nearMissKeywords: string[];
  nearMissFallback: boolean;
  checksum: string | null;
  checksumRequired: boolean;
}

export interface TorkPiiSignal {
  country: string;
  regex: RegExp;
  keywords: string[];
  wholeWordKeywords: string[];
  activates: string;
}

export interface TorkPiiCountry {
  code: string;
  name: string;
  callingCode: string;
  bloc: boolean;
  patterns: string[];
}

export const TORK_PII_REGISTRY_VERSION = "1.2.0";
export const TORK_PII_CONTENT_HASH = "cfd4f61ebaf45e743ba20d995d5ed585dd284778a2b3202ba917d71164b4fa26";

/** The keyword gate is ASYMMETRIC — see README.md, rule 3. */
export const TORK_PII_KEYWORD_WINDOW_BEFORE = 60;
export const TORK_PII_KEYWORD_WINDOW_AFTER = 40;
export const TORK_PII_CONTEXT_WINDOW = 60;
export const TORK_PII_LABEL_WINDOW = 60;
export const TORK_PII_LABEL_REACH = 25;

export const TORK_PII_NEAR_MISS_REDACTION = "[NATIONAL_ID_REDACTED]";
export const TORK_PII_NEAR_MISS_TYPE = "national_id_near_miss";
export const TORK_PII_NEAR_MISS_KINDS: string[] = ["health_id", "national_id", "tax_id"];

export const TORK_PII_TABLE_DELIMITERS: string[] = ["\t", "|", ";", ","];
export const TORK_PII_TABLE_MAX_HEADER_LENGTH = 32;
export const TORK_PII_TABLE_MAX_HEADER_WORDS = 4;
export const TORK_PII_TABLE_MIN_ROWS = 3;
export const TORK_PII_TABLE_MIN_COMMA_COLUMNS = 3;

export const TORK_PII_LABELS: string[] = [
  "AADHAAR",
  "ABN",
  "ACN",
  "BVN",
  "CA_PASSPORT",
  "CA_PHONE",
  "CA_POSTAL",
  "CNIC",
  "CNPJ",
  "CODICE_FISCALE",
  "CPF",
  "EMIRATES_ID",
  "GHANA_CARD",
  "IFSC",
  "ITIN",
  "KRA_PIN",
  "MEDICARE",
  "MYKAD",
  "MY_NUMBER",
  "NATIONAL_ID",
  "NHS",
  "NIK",
  "NIN",
  "NINO",
  "NRIC",
  "PAN",
  "PASSPORT",
  "PHONE",
  "PINCODE",
  "PO_BOX",
  "RESIDENT_ID",
  "RFC",
  "RRN",
  "SIN",
  "SORT_CODE",
  "TAN",
  "TAX_ID",
  "TFN",
  "UK_POSTCODE",
  "ZA_ID",
];

export const TORK_PII_REFERENCE_LABELS: string[] = [
  "order",
  "invoice",
  "purchase order",
  "po no",
  "po number",
  "job number",
  "job no",
  "booking",
  "tracking",
  "consignment",
  "waybill",
  "airway bill",
  "awb",
  "docket",
  "quote",
  "quotation",
  "ticket",
  "receipt",
  "serial number",
  "asset tag",
  "part number",
  "stock code",
  "batch",
  "shipment",
  "dispatch note",
  "delivery note",
  "work order",
  "contract number",
  "policy number",
  "meter number",
  "case id",
  "bestelling",
  "bestelnommer",
  "faktuur",
  "kwotasie",
  "commande",
  "facture",
  "devis",
  "bon de livraison",
  "expédition",
  "expedition",
  "pedido",
  "fatura",
  "factura",
  "orçamento",
  "orcamento",
  "presupuesto",
  "remito",
  "pesanan",
  "nombor pesanan",
  "invois",
  "sebut harga",
  "penghantaran",
  "resit",
  "आदेश",
  "क्रय आदेश",
  "चालान",
  "कोटेशन",
  "रसीद",
  "آرڈر",
  "انوائس",
  "رسید",
  "کوٹیشن",
  "ترسیل",
  "طلب",
  "أمر شراء",
  "فاتورة",
  "عرض سعر",
  "إيصال",
  "شحنة",
  "بوليصة",
  "注文",
  "注文番号",
  "発注",
  "発注番号",
  "請求書",
  "請求番号",
  "伝票",
  "伝票番号",
  "見積",
  "見積番号",
  "管理番号",
  "在庫番号",
  "受注",
  "出荷",
  "订单",
  "訂單",
  "订单编号",
  "訂單編號",
  "发票",
  "發票",
  "采购",
  "採購",
  "报价",
  "報價",
  "运单",
  "運單",
  "物料编号",
  "物料編號",
  "库存",
  "庫存",
  "주문",
  "주문번호",
  "구매주문",
  "송장",
  "견적",
  "견적서",
  "운송장",
  "자재번호",
  "재고번호",
  "ใบสั่งซื้อ",
  "เลขที่ใบสั่งซื้อ",
  "ใบแจ้งหนี้",
  "ใบเสนอราคา",
  "ใบส่งของ",
  "รหัสพัสดุ",
  "ใบงาน",
];

export const TORK_PII_GENERIC_ID_KEYWORDS: string[] = [
  "national id",
  "national identity",
  "national identification",
  "national number",
  "national code",
  "identity number",
  "identification number",
  "id number",
  "citizen id",
  "citizen number",
  "resident id",
  "resident number",
  "civil id",
  "civil number",
  "civil registration",
  "personal number",
  "personal identity",
  "personal code",
  "personal id",
  "tax identification",
  "tax reference",
  "taxpayer number",
  "taxpayer id",
];

export const TORK_PII_LOCAL_ID_KEYWORDS: string[] = [
  "cedula",
  "cédula",
  "iqama",
  "nadra",
  "cnic",
  "aadhaar",
  "voen",
  "vöen",
  "егн",
  "oib",
  "cpr-nummer",
  "cpr nummer",
  "kennitala",
  "personnummer",
  "adoazonosito",
  "adóazonosító",
  "szemelyi azonosito",
  "személyi azonosító",
  "kimlik",
  "рнокпп",
  "nid number",
  "sars income tax",
];

export const TORK_PII_COUNTRIES: TorkPiiCountry[] = [
  { code: "AU", name: "Australia", callingCode: "61", bloc: false, patterns: ["au_tfn", "au_abn", "au_medicare", "au_acn", "au_phone_intl"] },
  { code: "US", name: "United States", callingCode: "1", bloc: false, patterns: ["us_itin", "us_passport_alpha"] },
  { code: "GB", name: "United Kingdom", callingCode: "44", bloc: false, patterns: ["uk_phone_full", "uk_sort_code", "uk_nino", "uk_nhs", "uk_postcode"] },
  { code: "EU", name: "European Union", callingCode: "", bloc: true, patterns: ["de_tax_id"] },
  { code: "AE", name: "United Arab Emirates", callingCode: "971", bloc: false, patterns: ["emirates_id", "uae_phone", "uae_landline", "po_box"] },
  { code: "SA", name: "Saudi Arabia", callingCode: "966", bloc: false, patterns: ["sa_national_id", "sa_phone"] },
  { code: "NG", name: "Nigeria", callingCode: "234", bloc: false, patterns: ["ng_nin", "ng_bvn", "ng_phone"] },
  { code: "IN", name: "India", callingCode: "91", bloc: false, patterns: ["in_aadhaar", "in_pan", "in_phone", "in_ifsc", "in_pincode"] },
  { code: "JP", name: "Japan", callingCode: "81", bloc: false, patterns: ["jp_my_number", "jp_phone_intl", "jp_phone_national"] },
  { code: "CN", name: "China", callingCode: "86", bloc: false, patterns: ["cn_resident_id", "cn_phone_intl", "cn_phone_national"] },
  { code: "KR", name: "South Korea", callingCode: "82", bloc: false, patterns: ["kr_rrn", "kr_phone_intl", "kr_phone_national"] },
  { code: "BR", name: "Brazil", callingCode: "55", bloc: false, patterns: ["br_cpf", "br_cnpj"] },
  { code: "CA", name: "Canada", callingCode: "1", bloc: false, patterns: ["ca_sin", "ca_phone", "ca_postal_code", "ca_passport"] },
  { code: "ZA", name: "South Africa", callingCode: "27", bloc: false, patterns: ["za_id_number", "za_phone"] },
  { code: "GH", name: "Ghana", callingCode: "233", bloc: false, patterns: ["gh_ghana_card"] },
  { code: "IT", name: "Italy", callingCode: "39", bloc: false, patterns: ["it_codice_fiscale"] },
  { code: "KE", name: "Kenya", callingCode: "254", bloc: false, patterns: ["ke_kra_pin"] },
  { code: "MU", name: "Mauritius", callingCode: "230", bloc: false, patterns: ["mu_tan"] },
  { code: "MX", name: "Mexico", callingCode: "52", bloc: false, patterns: ["mx_rfc"] },
  { code: "MY", name: "Malaysia", callingCode: "60", bloc: false, patterns: ["my_mykad"] },
  { code: "PK", name: "Pakistan", callingCode: "92", bloc: false, patterns: ["pk_cnic"] },
  { code: "SG", name: "Singapore", callingCode: "65", bloc: false, patterns: ["sg_nric"] },
  { code: "TH", name: "Thailand", callingCode: "66", bloc: false, patterns: ["th_national_id"] },
  { code: "ID", name: "Indonesia", callingCode: "62", bloc: false, patterns: ["id_nik"] },
];

export const TORK_PII_PATTERNS: TorkPiiPattern[] = [
  {
    name: "au_tfn",
    country: "AU",
    kind: "tax_id",
    regex: new RegExp("\\b\\d{3}[ \\t]?\\d{3}[ \\t]?\\d{3}\\b", "g"),
    redaction: "[TFN_REDACTED]",
    type: "au_tfn",
    label: "TFN",
    requiresKeyword: true,
    alwaysOn: true,
    keywords: ["tfn", "tax file", "tax number"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: true,
    checksum: "au_tfn",
    checksumRequired: true,
  },
  {
    name: "au_abn",
    country: "AU",
    kind: "company",
    regex: new RegExp("\\b\\d{2}[ \\t]?\\d{3}[ \\t]?\\d{3}[ \\t]?\\d{3}\\b", "g"),
    redaction: "[ABN_REDACTED]",
    type: "au_abn",
    label: "ABN",
    requiresKeyword: true,
    alwaysOn: true,
    keywords: ["abn", "business number", "australian business"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: "au_abn",
    checksumRequired: true,
  },
  {
    name: "au_medicare",
    country: "AU",
    kind: "health_id",
    regex: new RegExp("\\b\\d{4}[ \\t]?\\d{5}[ \\t]?\\d{1}\\b", "g"),
    redaction: "[MEDICARE_REDACTED]",
    type: "au_medicare",
    label: "MEDICARE",
    requiresKeyword: true,
    alwaysOn: true,
    keywords: ["medicare"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: "au_medicare",
    checksumRequired: false,
  },
  {
    name: "au_acn",
    country: "AU",
    kind: "company",
    regex: new RegExp("\\b\\d{3}[ \\t]?\\d{3}[ \\t]?\\d{3}\\b", "g"),
    redaction: "[ACN_REDACTED]",
    type: "au_acn",
    label: "ACN",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["acn", "company number", "australian company"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "au_phone_intl",
    country: "AU",
    kind: "phone",
    regex: new RegExp("\\+61[ \\t]?[2-478](?:[ \\t]?\\d){8}\\b", "g"),
    redaction: "[PHONE_REDACTED]",
    type: "au_phone",
    label: "PHONE",
    requiresKeyword: false,
    alwaysOn: false,
    keywords: [],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "us_itin",
    country: "US",
    kind: "tax_id",
    regex: new RegExp("\\b9\\d{2}-[7-9]\\d-\\d{4}\\b", "g"),
    redaction: "[ITIN_REDACTED]",
    type: "us_itin",
    label: "ITIN",
    requiresKeyword: false,
    alwaysOn: false,
    keywords: [],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "us_passport_alpha",
    country: "US",
    kind: "passport",
    regex: new RegExp("\\b[A-Z]\\d{8}\\b", "g"),
    redaction: "[PASSPORT_REDACTED]",
    type: "us_passport",
    label: "PASSPORT",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["passport"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "uk_phone_full",
    country: "GB",
    kind: "phone",
    regex: new RegExp("(?:\\+44[ \\t]?|\\b0)(?:7\\d{3}|\\d{2,4})[ \\t]?\\d{3,4}[ \\t]?\\d{3,4}\\b", "g"),
    redaction: "[PHONE_REDACTED]",
    type: "uk_phone",
    label: "PHONE",
    requiresKeyword: false,
    alwaysOn: false,
    keywords: [],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "uk_sort_code",
    country: "GB",
    kind: "bank",
    regex: new RegExp("\\b\\d{2}-\\d{2}-\\d{2}\\b", "g"),
    redaction: "[SORT_CODE_REDACTED]",
    type: "uk_sort_code",
    label: "SORT_CODE",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["sort code", "sort-code", "bank", "account"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "uk_nino",
    country: "GB",
    kind: "national_id",
    regex: new RegExp("\\b[A-Z]{2}[ \\t]?\\d{2}[ \\t]?\\d{2}[ \\t]?\\d{2}[ \\t]?[A-D]\\b", "g"),
    redaction: "[NINO_REDACTED]",
    type: "national_id",
    label: "NINO",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["national insurance", "ni number", "nino", "ni:", "insurance number"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "uk_nhs",
    country: "GB",
    kind: "health_id",
    regex: new RegExp("\\b\\d{3}[ \\t]?\\d{3}[ \\t]?\\d{4}\\b", "g"),
    redaction: "[NHS_REDACTED]",
    type: "health_id",
    label: "NHS",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["nhs", "national health", "nhs number", "health service"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: true,
    checksum: "uk_nhs",
    checksumRequired: true,
  },
  {
    name: "uk_postcode",
    country: "GB",
    kind: "postcode",
    regex: new RegExp("\\b[A-Z]{1,2}\\d[A-Z\\d]?[ \\t]?\\d[A-Z]{2}\\b", "g"),
    redaction: "[UK_POSTCODE_REDACTED]",
    type: "postal_code",
    label: "UK_POSTCODE",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["postcode", "post code", "uk", "united kingdom", "britain", "england", "scotland", "wales"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "de_tax_id",
    country: "EU",
    kind: "tax_id",
    regex: new RegExp("\\b\\d{2}[ \\t]?\\d{3}[ \\t]?\\d{3}[ \\t]?\\d{3}\\b", "g"),
    redaction: "[TAX_ID_REDACTED]",
    type: "de_tax_id",
    label: "TAX_ID",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["steuer", "tax id", "steuernummer", "idnr", "steueridentifikation"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: "de_steuer_id",
    checksumRequired: false,
  },
  {
    name: "emirates_id",
    country: "AE",
    kind: "national_id",
    regex: new RegExp("\\b784-?\\d{4}-?\\d{7}-?\\d\\b", "g"),
    redaction: "[EMIRATES_ID_REDACTED]",
    type: "emirates_id",
    label: "EMIRATES_ID",
    requiresKeyword: false,
    alwaysOn: false,
    keywords: [],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: "ae_emirates_id",
    checksumRequired: false,
  },
  {
    name: "uae_phone",
    country: "AE",
    kind: "phone",
    regex: new RegExp("(?:\\+971[ \\t]?|\\b0)5[0-9][ \\t]?\\d{3}[ \\t]?\\d{4}\\b", "g"),
    redaction: "[PHONE_REDACTED]",
    type: "uae_phone",
    label: "PHONE",
    requiresKeyword: false,
    alwaysOn: false,
    keywords: [],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "uae_landline",
    country: "AE",
    kind: "phone",
    regex: new RegExp("(?:\\+971[ \\t]?|\\b0)[2-4679][ \\t]?\\d{3}[ \\t]?\\d{4}\\b", "g"),
    redaction: "[PHONE_REDACTED]",
    type: "uae_landline",
    label: "PHONE",
    requiresKeyword: false,
    alwaysOn: false,
    keywords: [],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "po_box",
    country: "AE",
    kind: "postcode",
    regex: new RegExp("\\b[Pp]\\.?[Oo]\\.?[ \\t]*[Bb]ox[ \\t]+\\d{3,6}\\b", "g"),
    redaction: "[PO_BOX_REDACTED]",
    type: "po_box",
    label: "PO_BOX",
    requiresKeyword: false,
    alwaysOn: false,
    keywords: [],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "sa_national_id",
    country: "SA",
    kind: "national_id",
    regex: new RegExp("\\b[12]\\d{9}\\b", "g"),
    redaction: "[NATIONAL_ID_REDACTED]",
    type: "sa_national_id",
    label: "NATIONAL_ID",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["national id", "iqama", "national identification", "resident id", "saudi id"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: "sa_national_id",
    checksumRequired: false,
  },
  {
    name: "sa_phone",
    country: "SA",
    kind: "phone",
    regex: new RegExp("(?:\\+966[ \\t]?|\\b0)5[0-9][ \\t]?\\d{3}[ \\t]?\\d{4}\\b", "g"),
    redaction: "[PHONE_REDACTED]",
    type: "sa_phone",
    label: "PHONE",
    requiresKeyword: false,
    alwaysOn: false,
    keywords: [],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "ng_nin",
    country: "NG",
    kind: "national_id",
    regex: new RegExp("\\b\\d{11}\\b", "g"),
    redaction: "[NIN_REDACTED]",
    type: "ng_nin",
    label: "NIN",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["nin", "national id", "national identification"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "ng_bvn",
    country: "NG",
    kind: "bank",
    regex: new RegExp("\\b\\d{11}\\b", "g"),
    redaction: "[BVN_REDACTED]",
    type: "ng_bvn",
    label: "BVN",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["bvn", "bank verification"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "ng_phone",
    country: "NG",
    kind: "phone",
    regex: new RegExp("(?:\\+234[ \\t]?|\\b0)[789]0[1-9][ \\t]?\\d{3}[ \\t]?\\d{4}\\b", "g"),
    redaction: "[PHONE_REDACTED]",
    type: "ng_phone",
    label: "PHONE",
    requiresKeyword: false,
    alwaysOn: false,
    keywords: [],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "in_aadhaar",
    country: "IN",
    kind: "national_id",
    regex: new RegExp("\\b\\d{4}[ \\t]?\\d{4}[ \\t]?\\d{4}\\b", "g"),
    redaction: "[AADHAAR_REDACTED]",
    type: "in_aadhaar",
    label: "AADHAAR",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["aadhaar", "aadhar", "uid", "unique identification", "aadhaar number"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: true,
    checksum: "verhoeff",
    checksumRequired: true,
  },
  {
    name: "in_pan",
    country: "IN",
    kind: "tax_id",
    regex: new RegExp("\\b[A-Z]{5}\\d{4}[A-Z]\\b", "g"),
    redaction: "[PAN_REDACTED]",
    type: "in_pan",
    label: "PAN",
    requiresKeyword: false,
    alwaysOn: false,
    keywords: [],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "in_phone",
    country: "IN",
    kind: "phone",
    regex: new RegExp("(?:\\+91[ \\t]?|\\b0|\\b)[6-9]\\d{4}[ \\t]?\\d{5}\\b", "g"),
    redaction: "[PHONE_REDACTED]",
    type: "in_phone",
    label: "PHONE",
    requiresKeyword: false,
    alwaysOn: false,
    keywords: [],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "in_ifsc",
    country: "IN",
    kind: "bank",
    regex: new RegExp("\\b[A-Z]{4}0[A-Z0-9]{6}\\b", "g"),
    redaction: "[IFSC_REDACTED]",
    type: "in_ifsc",
    label: "IFSC",
    requiresKeyword: false,
    alwaysOn: false,
    keywords: [],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "in_pincode",
    country: "IN",
    kind: "postcode",
    regex: new RegExp("\\b[1-9]\\d{5}\\b", "g"),
    redaction: "[PINCODE_REDACTED]",
    type: "in_pincode",
    label: "PINCODE",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["pin code", "pincode", "postal code", "zip", "address"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "jp_my_number",
    country: "JP",
    kind: "national_id",
    regex: new RegExp("\\b\\d{4}[ \\t]?\\d{4}[ \\t]?\\d{4}\\b", "g"),
    redaction: "[MY_NUMBER_REDACTED]",
    type: "jp_my_number",
    label: "MY_NUMBER",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["my number", "individual number", "マイナンバー"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: true,
    checksum: "jp_my_number",
    checksumRequired: true,
  },
  {
    name: "jp_phone_intl",
    country: "JP",
    kind: "phone",
    regex: new RegExp("\\+81[ \\t-]?[0-9]{1,4}[ \\t-]?\\d{2,4}[ \\t-]?\\d{4}\\b", "g"),
    redaction: "[PHONE_REDACTED]",
    type: "jp_phone",
    label: "PHONE",
    requiresKeyword: false,
    alwaysOn: false,
    keywords: [],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "jp_phone_national",
    country: "JP",
    kind: "phone",
    regex: new RegExp("\\b0[0-9]{1,4}[ \\t-]?\\d{2,4}[ \\t-]?\\d{4}\\b", "g"),
    redaction: "[PHONE_REDACTED]",
    type: "jp_phone",
    label: "PHONE",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["phone", "telephone", "tel", "mobile", "cell", "fax", "call", "contact", "whatsapp", "hotline", "landline", "電話", "電話番号", "携帯", "携帯番号", "でんわ", "电话", "手机", "手機", "전화", "휴대", "휴대폰", "연락처"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "cn_resident_id",
    country: "CN",
    kind: "national_id",
    regex: new RegExp("\\b\\d{6}(?:19|20)\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])\\d{3}[0-9Xx]\\b", "g"),
    redaction: "[RESIDENT_ID_REDACTED]",
    type: "cn_resident_id",
    label: "RESIDENT_ID",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["resident id", "resident identity", "identity card", "id card", "national id", "id number", "id no", "id:", "id =", "identity number", "hukou", "身份证", "身份證", "居民身份证", "居民身份證"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: true,
    checksum: "cn_resident_id",
    checksumRequired: true,
  },
  {
    name: "cn_phone_intl",
    country: "CN",
    kind: "phone",
    regex: new RegExp("\\+86[ \\t-]?1[3-9]\\d{9}\\b", "g"),
    redaction: "[PHONE_REDACTED]",
    type: "cn_phone",
    label: "PHONE",
    requiresKeyword: false,
    alwaysOn: false,
    keywords: [],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "cn_phone_national",
    country: "CN",
    kind: "phone",
    regex: new RegExp("\\b1[3-9]\\d{9}\\b", "g"),
    redaction: "[PHONE_REDACTED]",
    type: "cn_phone",
    label: "PHONE",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["phone", "telephone", "tel", "mobile", "cell", "fax", "call", "contact", "whatsapp", "hotline", "landline", "電話", "電話番号", "携帯", "携帯番号", "でんわ", "电话", "手机", "手機", "전화", "휴대", "휴대폰", "연락처"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "kr_rrn",
    country: "KR",
    kind: "national_id",
    regex: new RegExp("\\b\\d{6}-?[1-4]\\d{6}\\b", "g"),
    redaction: "[RRN_REDACTED]",
    type: "kr_rrn",
    label: "RRN",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["resident registration", "resident number", "registration number", "rrn", "jumin", "juminbeonho", "national id", "id number", "id no", "id:", "id =", "identity number", "주민등록번호", "주민번호"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: "kr_rrn",
    checksumRequired: false,
  },
  {
    name: "kr_phone_intl",
    country: "KR",
    kind: "phone",
    regex: new RegExp("\\+82[ \\t-]?1[016789][ \\t-]?\\d{3,4}[ \\t-]?\\d{4}\\b", "g"),
    redaction: "[PHONE_REDACTED]",
    type: "kr_phone",
    label: "PHONE",
    requiresKeyword: false,
    alwaysOn: false,
    keywords: [],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "kr_phone_national",
    country: "KR",
    kind: "phone",
    regex: new RegExp("\\b01[016789][ \\t-]?\\d{3,4}[ \\t-]?\\d{4}\\b", "g"),
    redaction: "[PHONE_REDACTED]",
    type: "kr_phone",
    label: "PHONE",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["phone", "telephone", "tel", "mobile", "cell", "fax", "call", "contact", "whatsapp", "hotline", "landline", "電話", "電話番号", "携帯", "携帯番号", "でんわ", "电话", "手机", "手機", "전화", "휴대", "휴대폰", "연락처"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "br_cpf",
    country: "BR",
    kind: "national_id",
    regex: new RegExp("\\b\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2}\\b", "g"),
    redaction: "[CPF_REDACTED]",
    type: "br_cpf",
    label: "CPF",
    requiresKeyword: false,
    alwaysOn: false,
    keywords: [],
    wholeWordKeywords: [],
    nearMissKeywords: ["cpf", "cadastro de pessoas", "receita federal"],
    nearMissFallback: true,
    checksum: "br_cpf",
    checksumRequired: true,
  },
  {
    name: "br_cnpj",
    country: "BR",
    kind: "company",
    regex: new RegExp("\\b\\d{2}\\.?\\d{3}\\.?\\d{3}\\/?\\d{4}-?\\d{2}\\b", "g"),
    redaction: "[CNPJ_REDACTED]",
    type: "br_cnpj",
    label: "CNPJ",
    requiresKeyword: false,
    alwaysOn: false,
    keywords: [],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: "br_cnpj",
    checksumRequired: true,
  },
  {
    name: "ca_sin",
    country: "CA",
    kind: "national_id",
    regex: new RegExp("\\b\\d{3}[- \\t]\\d{3}[- \\t]\\d{3}\\b", "g"),
    redaction: "[SIN_REDACTED]",
    type: "ca_sin",
    label: "SIN",
    requiresKeyword: false,
    alwaysOn: false,
    keywords: ["sin", "social insurance", "canada revenue", "cra", "employment insurance"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: "ca_sin",
    checksumRequired: false,
  },
  {
    name: "ca_phone",
    country: "CA",
    kind: "phone",
    regex: new RegExp("\\b(\\+?1[-. \\t]?)?\\(?\\d{3}\\)?[-. \\t]\\d{3}[-. \\t]\\d{4}\\b", "g"),
    redaction: "[CA_PHONE_REDACTED]",
    type: "phone",
    label: "CA_PHONE",
    requiresKeyword: false,
    alwaysOn: false,
    keywords: ["phone", "mobile", "cell", "tel"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "ca_postal_code",
    country: "CA",
    kind: "postcode",
    regex: new RegExp("\\b[A-Za-z]\\d[A-Za-z][ \\t-]?\\d[A-Za-z]\\d\\b", "g"),
    redaction: "[CA_POSTAL_REDACTED]",
    type: "postal_code",
    label: "CA_POSTAL",
    requiresKeyword: false,
    alwaysOn: false,
    keywords: ["postal", "zip", "post code", "mailing"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "ca_passport",
    country: "CA",
    kind: "passport",
    regex: new RegExp("\\b[A-Za-z]{2}\\d{6}\\b", "g"),
    redaction: "[CA_PASSPORT_REDACTED]",
    type: "passport",
    label: "CA_PASSPORT",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["passport", "travel document", "citizenship"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "za_id_number",
    country: "ZA",
    kind: "national_id",
    regex: new RegExp("\\b(\\d{2})(0[1-9]|1[0-2])(0[1-9]|[12]\\d|3[01])(\\d{4})(0|1)(\\d{2})\\b", "g"),
    redaction: "[ZA_ID_REDACTED]",
    type: "za_id_number",
    label: "ZA_ID",
    requiresKeyword: false,
    alwaysOn: false,
    keywords: [],
    wholeWordKeywords: [],
    nearMissKeywords: ["sa id", "rsa id", "south african id", "suid-afrikaanse id", "id no", "id-nommer", "home affairs"],
    nearMissFallback: true,
    checksum: "za_id",
    checksumRequired: true,
  },
  {
    name: "za_phone",
    country: "ZA",
    kind: "phone",
    regex: new RegExp("(?:\\+27[ \\t]?|\\b0)[6-8]\\d[ \\t]?\\d{3}[ \\t]?\\d{4}\\b", "g"),
    redaction: "[PHONE_REDACTED]",
    type: "za_phone",
    label: "PHONE",
    requiresKeyword: false,
    alwaysOn: false,
    keywords: [],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "gh_ghana_card",
    country: "GH",
    kind: "national_id",
    regex: new RegExp("\\b[A-Z]{3}-\\d{8,9}-[0-9A-Z]\\b", "g"),
    redaction: "[GHANA_CARD_REDACTED]",
    type: "gh_ghana_card",
    label: "GHANA_CARD",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["ghana card", "ghanacard", "ghana revenue", "nia pin", "personal id number", "gra tin"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "it_codice_fiscale",
    country: "IT",
    kind: "tax_id",
    regex: new RegExp("\\b[A-Z]{6}\\d{2}[ABCDEHLMPRST]\\d{2}[A-Z]\\d{3}[A-Z]\\b", "g"),
    redaction: "[CODICE_FISCALE_REDACTED]",
    type: "it_codice_fiscale",
    label: "CODICE_FISCALE",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["codice fiscale", "cod. fisc", "cod.fisc", "c.f.", "anagrafe tributaria", "tessera sanitaria"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: true,
    checksum: "it_codice_fiscale",
    checksumRequired: true,
  },
  {
    name: "ke_kra_pin",
    country: "KE",
    kind: "tax_id",
    regex: new RegExp("\\b[AP]\\d{9}[A-Z]\\b", "g"),
    redaction: "[KRA_PIN_REDACTED]",
    type: "ke_kra_pin",
    label: "KRA_PIN",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["kra pin", "kra", "tax pin", "itax", "pin certificate", "personal identification number"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "mu_tan",
    country: "MU",
    kind: "tax_id",
    regex: new RegExp("\\b[123578]\\d{7}\\b", "g"),
    redaction: "[TAN_REDACTED]",
    type: "mu_tan",
    label: "TAN",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["tax account number", "mauritius revenue", "tan ", "tan:", "tan no", "tan number", "mra tan"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "mx_rfc",
    country: "MX",
    kind: "tax_id",
    regex: new RegExp("\\b[A-Z]{4}\\d{6}[A-Z0-9]{3}\\b", "g"),
    redaction: "[RFC_REDACTED]",
    type: "mx_rfc",
    label: "RFC",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["rfc", "homoclave", "registro federal de contribuyentes", "contribuyentes", "constancia de situación fiscal"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "my_mykad",
    country: "MY",
    kind: "national_id",
    regex: new RegExp("\\b\\d{6}-?\\d{2}-?\\d{4}\\b", "g"),
    redaction: "[MYKAD_REDACTED]",
    type: "my_mykad",
    label: "MYKAD",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["mykad", "my kad", "kad pengenalan", "no. kad pengenalan", "nric", "ic number", "no. ic", "mykid"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "pk_cnic",
    country: "PK",
    kind: "national_id",
    regex: new RegExp("\\b\\d{5}-?\\d{7}-?\\d\\b", "g"),
    redaction: "[CNIC_REDACTED]",
    type: "pk_cnic",
    label: "CNIC",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["cnic", "nadra", "nic number", "identity card number", "شناختی کارڈ", "شناختی"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
  {
    name: "sg_nric",
    country: "SG",
    kind: "national_id",
    regex: new RegExp("\\b[STFGM]\\d{7}[A-Z]\\b", "g"),
    redaction: "[NRIC_REDACTED]",
    type: "sg_nric",
    label: "NRIC",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["nric", "fin number", "fin no", "fin:", "identity card", "identification number", "cpf", "singpass"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: true,
    checksum: "sg_nric",
    checksumRequired: true,
  },
  {
    name: "th_national_id",
    country: "TH",
    kind: "national_id",
    regex: new RegExp("\\b\\d-?\\d{4}-?\\d{5}-?\\d{2}-?\\d\\b", "g"),
    redaction: "[NATIONAL_ID_REDACTED]",
    type: "th_national_id",
    label: "NATIONAL_ID",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["national id", "thai id", "เลขประจำตัวประชาชน", "บัตรประชาชน", "เลขบัตร", "promptpay"],
    wholeWordKeywords: [],
    nearMissKeywords: [],
    nearMissFallback: true,
    checksum: "th_national_id",
    checksumRequired: true,
  },
  {
    name: "id_nik",
    country: "ID",
    kind: "national_id",
    regex: new RegExp("\\b\\d{16}\\b", "g"),
    redaction: "[NIK_REDACTED]",
    type: "id_nik",
    label: "NIK",
    requiresKeyword: true,
    alwaysOn: false,
    keywords: ["nomor induk kependudukan", "kartu tanda penduduk", "dukcapil"],
    wholeWordKeywords: ["nik", "e-ktp", "ektp", "ktp", "npwp"],
    nearMissKeywords: [],
    nearMissFallback: false,
    checksum: null,
    checksumRequired: false,
  },
];

// Activation, in evaluation order. One signal per country is enough; stop at
// the first that matches. An empty keyword list means the shape alone decides.
export const TORK_PII_SIGNALS: TorkPiiSignal[] = [
  {
    country: "AU",
    regex: new RegExp("\\b\\d{3}\\s\\d{3}\\s\\d{3}\\b", ""),
    keywords: ["tfn", "tax file", "medicare"],
    wholeWordKeywords: [],
    activates: "AU",
  },
  {
    country: "AU",
    regex: new RegExp("\\b\\d{4}\\s\\d{5}\\s\\d{1}\\b", ""),
    keywords: [],
    wholeWordKeywords: [],
    activates: "AU",
  },
  {
    country: "AU",
    regex: new RegExp("\\b(0[2-9]|\\+61)\\d{8,9}\\b", ""),
    keywords: ["au", "australia", "australian"],
    wholeWordKeywords: [],
    activates: "AU",
  },
  {
    country: "GB",
    regex: new RegExp("\\b[A-Z]{2}[ \\t]?\\d{2}[ \\t]?\\d{2}[ \\t]?\\d{2}[ \\t]?[A-D]\\b", "i"),
    keywords: ["national insurance", "ni number", "nino", "ni:"],
    wholeWordKeywords: [],
    activates: "GB",
  },
  {
    country: "GB",
    regex: new RegExp("\\b[A-Z]{1,2}\\d{1,2}[ \\t]?\\d[A-Z]{2}\\b", ""),
    keywords: ["uk", "united kingdom", "britain", "postcode"],
    wholeWordKeywords: [],
    activates: "GB",
  },
  {
    country: "GB",
    regex: new RegExp("\\b(\\+44|0044)\\d{10}\\b", ""),
    keywords: ["uk", "united kingdom", "britain"],
    wholeWordKeywords: [],
    activates: "GB",
  },
  {
    country: "CA",
    regex: new RegExp("\\b\\d{3}[- \\t]\\d{3}[- \\t]\\d{3}\\b", ""),
    keywords: ["sin", "social insurance", "canada revenue", "cra", "employment insurance"],
    wholeWordKeywords: [],
    activates: "CA",
  },
  {
    country: "CA",
    regex: new RegExp("\\b[A-Za-z]\\d[A-Za-z][ \\t]?\\d[A-Za-z]\\d\\b", ""),
    keywords: ["canada", "canadian", "postal code", "province"],
    wholeWordKeywords: [],
    activates: "CA",
  },
  {
    country: "ZA",
    regex: new RegExp("\\b\\d{13}\\b", ""),
    keywords: ["id number", "identity number", "south africa", "sa id", "rsa", "popia", "fica"],
    wholeWordKeywords: [],
    activates: "ZA",
  },
  {
    country: "ZA",
    regex: new RegExp("\\b(\\+27|0)[6-8]\\d{8}\\b", ""),
    keywords: ["south africa", "za", "johannesburg", "cape town", "durban", "pretoria"],
    wholeWordKeywords: [],
    activates: "ZA",
  },
  {
    country: "DE",
    regex: new RegExp("\\b[1-9]\\d{10}\\b", ""),
    keywords: ["steuer", "steuernummer", "finanzamt", "tax id", "german"],
    wholeWordKeywords: [],
    activates: "DE",
  },
  {
    country: "DE",
    regex: new RegExp("\\b(\\+49|0049)\\d{10,11}\\b", ""),
    keywords: ["germany", "german", "deutschland", "de"],
    wholeWordKeywords: [],
    activates: "DE",
  },
  {
    country: "NG",
    regex: new RegExp("\\b\\d{11}\\b", ""),
    keywords: ["bvn", "nin", "bank verification", "nigeria", "nigerian"],
    wholeWordKeywords: [],
    activates: "NG",
  },
  {
    country: "NG",
    regex: new RegExp("\\b(\\+234|0)[7-9]\\d{9}\\b", ""),
    keywords: ["nigeria", "nigerian", "lagos", "abuja"],
    wholeWordKeywords: [],
    activates: "NG",
  },
  {
    country: "AE",
    regex: new RegExp("\\b784[- \\t]\\d{4}[- \\t]\\d{7}[- \\t]\\d{1}\\b", ""),
    keywords: [],
    wholeWordKeywords: [],
    activates: "AE",
  },
  {
    country: "AE",
    regex: new RegExp("\\b(\\+971|00971)\\d{9}\\b", ""),
    keywords: ["uae", "emirates", "dubai", "abu dhabi"],
    wholeWordKeywords: [],
    activates: "AE",
  },
  {
    country: "IN",
    regex: new RegExp("\\b[A-Z]{5}\\d{4}[A-Z]{1}\\b", ""),
    keywords: [],
    wholeWordKeywords: [],
    activates: "IN",
  },
  {
    country: "IN",
    regex: new RegExp("\\b\\d{4}\\s\\d{4}\\s\\d{4}\\b", ""),
    keywords: ["aadhaar", "aadhar", "india", "indian"],
    wholeWordKeywords: [],
    activates: "IN",
  },
  {
    country: "SA",
    regex: new RegExp("\\b1\\d{9}\\b", ""),
    keywords: ["saudi", "ksa", "riyadh", "national id", "iqama"],
    wholeWordKeywords: [],
    activates: "SA",
  },
  {
    country: "SA",
    regex: new RegExp("\\b(\\+966|00966)\\d{9}\\b", ""),
    keywords: ["saudi", "ksa", "riyadh"],
    wholeWordKeywords: [],
    activates: "SA",
  },
  {
    country: "BR",
    regex: new RegExp("\\b\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}\\b", ""),
    keywords: ["cpf", "brazil", "brasil", "brazilian"],
    wholeWordKeywords: [],
    activates: "BR",
  },
  {
    country: "BR",
    regex: new RegExp("\\b(\\+55|0055)\\d{11}\\b", ""),
    keywords: ["brazil", "brasil"],
    wholeWordKeywords: [],
    activates: "BR",
  },
  {
    country: "JP",
    regex: new RegExp("\\b\\d{4}[ \\t]?\\d{4}[ \\t]?\\d{4}\\b", ""),
    keywords: ["my number", "individual number", "マイナンバー", "個人番号", "japan", "japanese", "日本", "tokyo", "osaka", "nagoya", "yokohama"],
    wholeWordKeywords: [],
    activates: "JP",
  },
  {
    country: "JP",
    regex: new RegExp("\\b(\\+81|0081)[ \\t]?\\d{1,4}[ \\t-]?\\d{2,4}[ \\t-]?\\d{4}\\b", ""),
    keywords: ["japan", "japanese", "日本", "tokyo", "osaka"],
    wholeWordKeywords: [],
    activates: "JP",
  },
  {
    country: "CN",
    regex: new RegExp("\\b\\d{17}[0-9Xx]\\b", ""),
    keywords: ["resident id", "resident identity", "identity card", "id card", "身份证", "身份證", "居民身份证", "china", "chinese", "prc", "beijing", "shanghai", "shenzhen", "guangzhou"],
    wholeWordKeywords: [],
    activates: "CN",
  },
  {
    country: "CN",
    regex: new RegExp("\\b(\\+86|0086)[ \\t]?1[3-9]\\d{9}\\b", ""),
    keywords: ["china", "chinese", "prc", "beijing", "shanghai", "shenzhen", "guangzhou"],
    wholeWordKeywords: [],
    activates: "CN",
  },
  {
    country: "KR",
    regex: new RegExp("\\b\\d{6}-?[1-8]\\d{6}\\b", ""),
    keywords: ["resident registration", "resident number", "rrn", "jumin", "주민등록번호", "주민번호", "korea", "korean", "seoul", "busan", "incheon"],
    wholeWordKeywords: [],
    activates: "KR",
  },
  {
    country: "KR",
    regex: new RegExp("\\b(\\+82|0082)[ \\t]?1[016789][ \\t-]?\\d{3,4}[ \\t-]?\\d{4}\\b", ""),
    keywords: ["korea", "korean", "seoul", "busan", "incheon"],
    wholeWordKeywords: [],
    activates: "KR",
  },
  {
    country: "GH",
    regex: new RegExp("\\b[A-Z]{3}-\\d{8,9}-[0-9A-Z]\\b", ""),
    keywords: ["ghana card", "ghanacard", "ghana", "accra", "kumasi", "nia pin", "gra tin"],
    wholeWordKeywords: [],
    activates: "GH",
  },
  {
    country: "GH",
    regex: new RegExp("\\b(\\+233|00233)[ \\t]?\\d{9}\\b", ""),
    keywords: ["ghana", "ghanaian", "accra", "kumasi", "tema"],
    wholeWordKeywords: [],
    activates: "GH",
  },
  {
    country: "IT",
    regex: new RegExp("\\b[A-Z]{6}\\d{2}[ABCDEHLMPRST]\\d{2}[A-Z]\\d{3}[A-Z]\\b", ""),
    keywords: ["codice fiscale", "cod. fisc", "c.f.", "anagrafe tributaria", "italy", "italia", "italian", "italiana", "roma", "milano", "napoli", "torino"],
    wholeWordKeywords: [],
    activates: "IT",
  },
  {
    country: "IT",
    regex: new RegExp("\\b(\\+39|0039)[ \\t]?\\d{9,11}\\b", ""),
    keywords: ["italy", "italia", "italian", "italiana", "roma", "milano", "napoli", "torino"],
    wholeWordKeywords: [],
    activates: "IT",
  },
  {
    country: "KE",
    regex: new RegExp("\\b[AP]\\d{9}[A-Z]\\b", ""),
    keywords: ["kra", "itax", "tax pin", "kenya", "kenyan", "nairobi", "mombasa", "kisumu"],
    wholeWordKeywords: [],
    activates: "KE",
  },
  {
    country: "KE",
    regex: new RegExp("\\b(\\+254|00254)[ \\t]?\\d{9}\\b", ""),
    keywords: ["kenya", "kenyan", "nairobi", "mombasa", "kisumu"],
    wholeWordKeywords: [],
    activates: "KE",
  },
  {
    country: "MU",
    regex: new RegExp("\\b[123578]\\d{7}\\b", ""),
    keywords: ["mauritius", "mauritian", "port louis", "mauritius revenue", "mra tan"],
    wholeWordKeywords: [],
    activates: "MU",
  },
  {
    country: "MU",
    regex: new RegExp("\\b(\\+230|00230)[ \\t]?\\d{7,8}\\b", ""),
    keywords: ["mauritius", "mauritian", "port louis"],
    wholeWordKeywords: [],
    activates: "MU",
  },
  {
    country: "MX",
    regex: new RegExp("\\b[A-Z]{4}\\d{6}[A-Z0-9]{3}\\b", ""),
    keywords: ["rfc", "homoclave", "contribuyentes", "mexico", "méxico", "mexican", "mexicano", "cdmx", "guadalajara", "monterrey"],
    wholeWordKeywords: [],
    activates: "MX",
  },
  {
    country: "MX",
    regex: new RegExp("\\b(\\+52|0052)[ \\t]?\\d{10}\\b", ""),
    keywords: ["mexico", "méxico", "mexican", "mexicano", "cdmx", "guadalajara", "monterrey"],
    wholeWordKeywords: [],
    activates: "MX",
  },
  {
    country: "MY",
    regex: new RegExp("\\b\\d{6}-\\d{2}-\\d{4}\\b", ""),
    keywords: ["mykad", "kad pengenalan", "nric", "malaysia", "malaysian", "kuala lumpur", "johor", "penang", "putrajaya", "selangor"],
    wholeWordKeywords: [],
    activates: "MY",
  },
  {
    country: "MY",
    regex: new RegExp("\\b\\d{12}\\b", ""),
    keywords: ["mykad", "my kad", "kad pengenalan", "mykid"],
    wholeWordKeywords: [],
    activates: "MY",
  },
  {
    country: "MY",
    regex: new RegExp("\\b(\\+60|0060)[ \\t]?\\d{9,10}\\b", ""),
    keywords: ["malaysia", "malaysian", "kuala lumpur", "johor", "penang"],
    wholeWordKeywords: [],
    activates: "MY",
  },
  {
    country: "PK",
    regex: new RegExp("\\b\\d{5}-\\d{7}-\\d\\b", ""),
    keywords: ["cnic", "nadra", "pakistan", "pakistani", "karachi", "lahore", "islamabad", "rawalpindi", "شناختی"],
    wholeWordKeywords: [],
    activates: "PK",
  },
  {
    country: "PK",
    regex: new RegExp("\\b\\d{13}\\b", ""),
    keywords: ["cnic", "nadra", "شناختی"],
    wholeWordKeywords: [],
    activates: "PK",
  },
  {
    country: "PK",
    regex: new RegExp("\\b(\\+92|0092)[ \\t]?3\\d{9}\\b", ""),
    keywords: ["pakistan", "pakistani", "karachi", "lahore", "islamabad"],
    wholeWordKeywords: [],
    activates: "PK",
  },
  {
    country: "SG",
    regex: new RegExp("\\b[STFGM]\\d{7}[A-Z]\\b", ""),
    keywords: ["nric", "singpass", "cpf", "iras", "singapore", "singaporean"],
    wholeWordKeywords: [],
    activates: "SG",
  },
  {
    country: "SG",
    regex: new RegExp("\\b(\\+65|0065)[ \\t]?[689]\\d{3}[ \\t]?\\d{4}\\b", ""),
    keywords: ["singapore", "singaporean"],
    wholeWordKeywords: [],
    activates: "SG",
  },
  {
    country: "TH",
    regex: new RegExp("\\b\\d-\\d{4}-\\d{5}-\\d{2}-\\d\\b", ""),
    keywords: ["national id", "thai", "thailand", "เลขประจำตัวประชาชน", "บัตรประชาชน", "bangkok", "promptpay"],
    wholeWordKeywords: [],
    activates: "TH",
  },
  {
    country: "TH",
    regex: new RegExp("\\b\\d{13}\\b", ""),
    keywords: ["thai id", "thailand", "เลขประจำตัวประชาชน", "บัตรประชาชน", "promptpay"],
    wholeWordKeywords: [],
    activates: "TH",
  },
  {
    country: "TH",
    regex: new RegExp("\\b(\\+66|0066)[ \\t]?\\d{9}\\b", ""),
    keywords: ["thailand", "thai", "bangkok", "phuket", "chiang mai"],
    wholeWordKeywords: [],
    activates: "TH",
  },
  {
    country: "ID",
    regex: new RegExp("\\b\\d{16}\\b", ""),
    keywords: ["nomor induk kependudukan", "kartu tanda penduduk", "dukcapil"],
    wholeWordKeywords: ["nik", "e-ktp", "ektp", "ktp", "npwp"],
    activates: "ID",
  },
  {
    country: "ID",
    regex: new RegExp("\\b(\\+62|0062)[ \\t]?\\d{9,12}\\b", ""),
    keywords: ["indonesia", "indonesian", "jakarta", "surabaya", "bandung", "medan", "bali"],
    wholeWordKeywords: [],
    activates: "ID",
  },
];
